import {escape,money,price} from './common.js';
export function cartView(lines,total) {
  const target=document.getElementById('checkout-items');
  target.innerHTML=lines.length?lines.map(line=>`<article class="checkout-cart-item"><div class="checkout-item-copy"><h2>${escape(line.producto?.nombre || 'Producto retirado')}</h2><p>${line.producto?price(line.producto)+' · '+line.producto.stock+' disponibles':'Este producto ya no está disponible. Quítalo para continuar.'}</p><label for="qty-${escape(line.productoId)}">Cantidad</label><div class="quantity-picker"><button data-cart-minus="${escape(line.productoId)}" aria-label="Reducir cantidad de ${escape(line.producto?.nombre || 'producto retirado')}">−</button><input id="qty-${escape(line.productoId)}" data-cart-quantity="${escape(line.productoId)}" type="number" min="1" max="99" value="${line.cantidad}" aria-label="Cantidad de ${escape(line.producto?.nombre || 'producto retirado')}"><button data-cart-plus="${escape(line.productoId)}" aria-label="Aumentar cantidad de ${escape(line.producto?.nombre || 'producto retirado')}">+</button></div><button class="text-link" data-cart-remove="${escape(line.productoId)}" aria-label="Quitar ${escape(line.producto?.nombre || 'producto retirado')} del carrito">Quitar</button></div><strong>${line.producto?money(Math.round(Number(line.producto.precio)*100)*line.cantidad):'—'}</strong></article>`).join(''):'<div class="shop-empty"><h2>Tu carrito está vacío.</h2><p>Encuentra tus esenciales en el catálogo.</p><a class="button button-primary" href="catalogo.html">Explorar productos →</a></div>';
  document.getElementById('checkout-summary').innerHTML=`<p>Subtotal <strong>${money(total)}</strong></p><p>Retiro en farmacia <strong>Sin costo de envío</strong></p><p>Entrega: cobertura y costo por coordinar.</p><p class="summary-total">Total de productos <strong>${money(total)}</strong></p>`;
}
export function orderCard(order) {
  const date=new Intl.DateTimeFormat('es-EC',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Guayaquil'}).format(new Date(order.createdAt));
  return `<article class="order-card shop-panel"><div class="order-id"><div><h2>Pedido ${escape(order.id.slice(0,8))}</h2><p>${escape(date)} · Ecuador continental</p></div><span class="product-label">Pendiente de confirmar</span></div><ul class="order-lines">${order.detalles.map(line=>`<li><span>${line.cantidad} × ${escape(line.nombreProducto)}</span><strong>${money(Math.round(Number(line.precioUnitario)*100)*line.cantidad)}</strong></li>`).join('')}</ul><p><strong>Total de productos: ${money(Math.round(Number(order.total)*100))}</strong></p><p>${order.entrega==='pickup'?'Retiro en farmacia':'Entrega por coordinar'} · ${escape(order.documento)}</p><p>La farmacia confirmará disponibilidad, pago y entrega.</p><a class="text-link" href="https://wa.me/593979275988?text=${encodeURIComponent('Hola, por favor confirmen el pedido '+order.id+'.') }" target="_blank" rel="noopener noreferrer">Consultar pedido por WhatsApp ↗</a></article>`;
}
export function confirmationView(order) {
  const target=document.getElementById('order-confirmation');target.hidden=false;target.innerHTML=`<div class="confirmation-check" aria-hidden="true">✓</div><h2 tabindex="-1">Tu pedido quedó registrado.</h2><p>Consulta la confirmación y el pago con la farmacia.</p>${orderCard(order)}<a href="pedidos.html" class="button button-primary">Ver mis pedidos →</a>`;target.querySelector('h2').focus();
  document.getElementById('checkout-content').hidden=true;
}
export function ordersView(result) {
  document.getElementById('orders-list').innerHTML=result.items.length?result.items.map(orderCard).join(''):'<p class="shop-empty">Todavía no tienes pedidos. Explora el catálogo para empezar.</p>';
}
