import {escape,price,priceMarkup,promotionRibbon} from './common.js';
const imagePath=value=>/^assets\/(?:images\/[a-z0-9-]+\.(?:jpg|png|webp|svg)|uploads\/[a-f0-9-]+\.webp)$/.test(value)?value:'assets/images/logo-reina-del-cisne.png';
export function productCard(product) {
  return `<article class="featured-card" aria-labelledby="name-${escape(product.id)}"><a class="featured-image" href="producto.html?id=${encodeURIComponent(product.id)}"><img src="${imagePath(product.imagen)}" alt="${escape(product.alt)}" loading="lazy">${product.stock===0?'<span>Agotado</span>':''}${promotionRibbon(product.descuentoPorcentaje)}</a><small>${escape({bienestar:'Bienestar',cuidado:'Cuidado personal',bebe:'Mamá y bebé'}[product.categoria])}</small><h3 id="name-${escape(product.id)}"><a href="producto.html?id=${encodeURIComponent(product.id)}">${escape(product.nombre)}</a></h3><p>${escape(product.descripcion)}</p><div class="featured-bottom">${priceMarkup(product)}<button class="text-link" data-customer-only data-add="${escape(product.id)}" ${product.stock===0?'disabled':''} aria-label="Agregar ${escape(product.nombre)} al carrito">Agregar →</button></div><p class="product-stock">${product.stock} unidades disponibles</p><label class="catalog-compare"><input type="checkbox" data-compare="${escape(product.id)}"> Comparar</label></article>`;
}
export function catalogView(products,target) {
  target.innerHTML=products.length?products.map(productCard).join(''):'<p class="shop-empty">No encontramos productos con esos filtros.</p>';
}
export function productView(product) {
  document.getElementById('product-detail').innerHTML=`<section class="product-detail-grid"><div><button type="button" id="zoom-product" class="product-main-image" aria-label="Ampliar imagen de ${escape(product.nombre)}"><img src="${imagePath(product.imagen)}" alt="${escape(product.alt)}"><span>⌕ Ampliar imagen</span></button></div><div class="product-detail-copy"><p class="eyebrow">${escape(product.categoria)}</p><h1>${escape(product.nombre)}</h1>${promotionRibbon(product.descuentoPorcentaje)}<div class="detail-price">${priceMarkup(product)}<span>${product.stock} unidades disponibles</span></div><p class="shop-lead">${escape(product.descripcion)}</p><form id="detail-add-form" data-customer-only><label for="detail-quantity">Cantidad</label><div class="quantity-picker"><button type="button" data-quantity="-1" aria-label="Reducir cantidad">−</button><input id="detail-quantity" type="number" min="1" max="${Math.max(1,Math.min(product.stock,99))}" value="1" required><button type="button" data-quantity="1" aria-label="Aumentar cantidad">+</button></div><button class="button button-primary" type="submit" ${product.stock===0?'disabled':''}>${product.stock?'Añadir al carrito →':'Producto agotado'}</button></form><p>Retiro en farmacia o entrega por coordinar.</p><a class="text-link" href="comparar.html">Comparar productos →</a></div></section>`;
}
export function promotionView(items) {
  document.getElementById('promotions-note').textContent=items.some(item=>item.vistaPrevia)?'Las campañas marcadas como vista previa son ejemplos y no aplican descuentos. Consulta las condiciones de las promociones vigentes.':'El descuento vigente se aplica al carrito y al pedido. Consulta disponibilidad con la farmacia.';
  document.getElementById('promotions-list').innerHTML=items.length?items.map(item=>`<article class="promotion-card">${promotionRibbon(item.descuentoPorcentaje,item.vistaPrevia)}<img src="${imagePath(item.imagen || item.producto.imagen)}" alt="${escape(item.alt || item.producto.alt)}" loading="lazy"><div class="promotion-copy"><span class="promotion-label">${escape(item.etiqueta)}${item.vistaPrevia?' · vista previa':''}</span><h3>${escape(item.titulo)}</h3><p>${escape(item.descripcion)}</p><a class="text-link" href="producto.html?id=${encodeURIComponent(item.productoId)}">Explorar producto →</a></div></article>`).join(''):'<p class="promotions-empty">Estamos preparando nuevas promociones. Vuelve pronto o consulta por WhatsApp.</p>';
}
export function comparisonView(products,selected) {
  document.getElementById('compare-picks').innerHTML=products.map(product=>`<label class="compare-pick"><input type="checkbox" data-pick="${escape(product.id)}" ${selected.includes(product.id)?'checked':''}><span>${escape(product.nombre)}</span></label>`).join('');
  const chosen=products.filter(product=>selected.includes(product.id));
  document.getElementById('comparison').innerHTML=chosen.length?`<table class="comparison-table"><caption>Comparación de productos seleccionados</caption><thead><tr><th scope="col">Característica</th>${chosen.map(p=>`<th scope="col">${escape(p.nombre)}</th>`).join('')}</tr></thead><tbody>${[['Precio',p=>price(p)],['Categoría',p=>escape(p.categoria)],['Descripción',p=>escape(p.descripcion)],['Disponibilidad',p=>p.stock+' unidades']].map(([label,read])=>`<tr><th scope="row">${label}</th>${chosen.map(p=>`<td>${read(p)}</td>`).join('')}</tr>`).join('')}<tr><th scope="row">Elegir</th>${chosen.map(p=>`<td><a class="text-link" href="producto.html?id=${encodeURIComponent(p.id)}">Ver producto →</a></td>`).join('')}</tr></tbody></table>`:'<p>Selecciona hasta cuatro productos para comparar.</p>';
}
