const {Router}=require('express');
const {rateLimit}=require('express-rate-limit');
const {query}=require('express-validator');
const {authenticate,roles}=require('../middleware/auth.cjs');
const V=require('../middleware/validation.cjs');
const {AppError}=require('../middleware/errors.cjs');
module.exports=config=> {
  const router=Router();const auth=authenticate(config);const admin=roles('admin');const buyer=roles('user','admin');
  const authController=require('../controllers/auth.cjs')(config);
  const products=require('../controllers/productos.cjs');
  const orders=require('../controllers/pedidos.cjs');
  const promos=require('../controllers/promociones.cjs');
  const limiter=rateLimit({windowMs:15*60*1000,limit:20,standardHeaders:'draft-8',legacyHeaders:false,handler:(req,res,next)=>next(new AppError(429,'RATE_LIMIT','Demasiados intentos. Espera unos minutos.'))});
  router.post('/auth/register',limiter,...V.register,authController.register);
  router.post('/auth/login',limiter,...V.login,authController.login);
  router.get('/auth/me',auth,authController.me);
  router.post('/auth/logout',auth,authController.logout);
  router.get('/productos',...V.catalog,products.list);
  router.get('/productos/:id',V.id,V.validated,products.find);
  router.post('/productos',auth,admin,...V.product,V.validated,products.create);
  router.put('/productos/:id',auth,admin,V.id,...V.productUpdate,V.validated,products.update);
  router.delete('/productos/:id',auth,admin,V.id,V.validated,products.remove);
  router.post('/pedidos',auth,buyer,...V.order,orders.create);
  router.get('/pedidos/mis-pedidos',auth,buyer,...V.pagination,orders.mine);
  router.get('/pedidos',auth,admin,...V.pagination,orders.all);
  router.put('/pedidos/:id/estado',auth,admin,V.id,...V.orderStatus,V.validated,orders.updateStatus);
  router.get('/promociones',promos.list);
  router.post('/promociones',auth,admin,...V.promotion,V.validated,promos.create);
  router.put('/promociones/:id',auth,admin,V.id,...V.promotion,V.validated,promos.update);
  router.delete('/promociones/:id',auth,admin,V.id,V.validated,promos.remove);
  router.get('/admin/tablas',auth,admin,query('tabla').isIn(['productos','usuarios','pedidos','detalles','promociones']),...V.pagination,require('../controllers/admin.cjs'));
  router.get('/admin/resumen',auth,admin,require('../controllers/admin-summary.cjs'));
  router.get('/salud',require('../controllers/salud.cjs'));
  return router;
};
